source "https://rubygems.org"

ruby "3.2.3"

# Core Rails dependencies

gem "rails", "~> 7.1.3"
gem "sqlite3", "~> 1.6"
gem "puma", "~> 6.4"
gem "sassc-rails"
gem "jbuilder"
gem "bootsnap", require: false

group :development, :test do
  gem "byebug"
end

group :development do
  gem "web-console"
  gem "listen"
  gem "spring"
  gem "spring-watcher-listen"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
